### ISSUE TITLE
apt-uprgade broken systemd dependencies

### ISSUE THREAD

**Issue by TheRoam** [pythops/jetson-nano-image#97] opened 2023-05-14 19:06 UTC
Hi, is it possible to apt-upgrade some way? or recommended at all?

Seems that systemd tries to upgrade and it throws an error "trying to overwrite /etc/sleep.conf file which is in package nvidia-l4t-init"

Sorry I'm very noob with system stuff but I really like this image consuming only 200MB RAM :)

**Comment by TheRoam** [comment] 2023-05-14 20:33
exact issue happening here:
https://qengineering.eu/install-ubuntu-20.04-on-jetson-nano.html#imTextObject_89_431_tab0

I will try if proposed solution (forcing upgrade) works

**Comment by pythops** [comment] 2023-05-14 21:04
Thanks,  I'll give a try this week. Maybe it's time for ubuntu 22.04 :D

**Comment by mrcmunir** [comment] 2023-05-15 07:54
This it's only happen in jetson nano due because nvidia-l4t 32x doesn't nvidia fix it for conflict in focal/jammy headers .
The workarround it's  re-run  sudo dpkg -i --force-overwrite with conflicted package .

**Comment by soo-shan** [comment] 2023-08-04 17:51
I'm not able to fix the issue basis any of the recommendation above
```
$ sudo apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libnss-systemd : Depends: systemd (= 245.4-4ubuntu3.22) but 245.4-4ubuntu3.21 is installed
 libpam-systemd : Depends: systemd (= 245.4-4ubuntu3.22) but 245.4-4ubuntu3.21 is installed
 systemd : Depends: libsystemd0 (= 245.4-4ubuntu3.21) but 245.4-4ubuntu3.22 is installed
 systemd-sysv : Depends: systemd (= 245.4-4ubuntu3.22) but 245.4-4ubuntu3.21 is installed
 systemd-timesyncd : Depends: systemd (= 245.4-4ubuntu3.22) but 245.4-4ubuntu3.21 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```
```
$ sudo apt --fix-broken install
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  systemd
Suggested packages:
  systemd-container policykit-1
The following packages will be upgraded:
  systemd
1 upgraded, 0 newly installed, 0 to remove and 89 not upgraded.
16 not fully installed or removed.
Need to get 3,500 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://ports.ubuntu.com/ubuntu-ports focal-updates/main arm64 systemd arm64 245.4-4ubuntu3.22 [3,500 kB]
Fetched 3,500 kB in 0s (7,074 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 76868 files and directories currently installed.)
Preparing to unpack .../systemd_245.4-4ubuntu3.22_arm64.deb ...
Unpacking systemd (245.4-4ubuntu3.22) over (245.4-4ubuntu3.21) ...
dpkg: error processing archive /var/cache/apt/archives/systemd_245.4-4ubuntu3.22_arm64.deb (--unpack):
 trying to overwrite '/etc/systemd/sleep.conf', which is also in package nvidia-l4t-init 32.7.3-20221122092935
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/systemd_245.4-4ubuntu3.22_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
```
$ sudo dpkg -i --force-overwrite  /var/cache/apt/archives/systemd_245.4-4ubuntu3.22_arm64.deb
dpkg: error: cannot access archive '/var/cache/apt/archives/systemd_245.4-4ubuntu3.22_arm64.deb': No such file or directory

```
pls suggest what steps can be taken next ?

**Comment by pythops** [comment] 2023-11-24 22:43
Can't reproduce this one. the upgrade works fine. 
I'll close this one feel free to comment if it's still ongoing issue and I'll take a deep look

**Closed by pythops** 2023-11-24 22:43 UTC

**Comment by soo-shan** [comment] 2024-01-24 15:46
For anyone facing the issue of `No such file or directory` while running `--force-overwrite` can use `sudo apt install --download-only systemd` to download the package into `/var/cache/apt/archives/` folder.
